version: '3'
services:
  app:
    build: .
    environment:
      MPLCONFIGDIR: /etc
    volumes:
      - .:/opt/data-volume
    working_dir: /opt/data-volume
    entrypoint:
      - python
      - /opt/app/run.py